time = ("Palmeiras", "Flamengo", "Fluminense", "São Paulo", "Bahia", "Athletico-PR", "Botafogo", "Coritiba", "Vasco da Gama", "Vitória", "Internacional", "Goiás", "Santos", "Ceará", "Corinthians", "Grêmio", "Cruzeiro", "Remo", "Chapecoense", "Mirassol")
print("-"*50)
print(f"Lista de times do brasileirão 2026: {time}")
print("-"*50)
print(f"Os primeiros 5 são: {time[:5]}")
print("-"*50)
print(f"Os 4 ultimos são: {time[-4:]}")
print("-"*50)
print(f"Os times em ordem alfabetica é: {sorted(time)}")