spring:
  application:
    name: spring-data-jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/libraryapi
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
#    hibernate: -- permite a geração de banco apartir de java (não recommendado em produção)
#      ddl-auto: update -- permite a geração de banco apartir de java (não recommendado em produção)