spring:
  application:
    name: nova-api-tarefas
  datasource:
    url: jdbc:postgresql://localhost:5432/tarefas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver